id: A8B9288DD
title: 'Rain of Accomplishments: A Song that Incorporates the Four Mindfulnesses from
  an Instruction on the View of the Middle Way'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:30:45.219879
  last_modified_at: 2022-03-01 01:30:45.219886
